In [98]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [99]:
df = pd.read_csv ('cl_merged.csv')

In [100]:
df

,beds,baths,size,size_units,lot_size,lot_size_units,zip_code,price,index
0,3,3.0,2850.0,sqft,4200.0,sqft,98119,1175000.0,1
1,3,2.0,2360.0,sqft,12196.8,sqft,98188,565000.0,4
2,3,3.5,1942.0,sqft,1603.0,sqft,98107,1187000.0,5
3,4,2.0,2060.0,sqft,4206.0,sqft,98144,1025000.0,9
4,3,2.5,1760.0,sqft,3630.0,sqft,98122,1135000.0,11
...,...,...,...,...,...,...,...,...,...
1012,3,2.0,1482.0,sqft,1085.0,sqft,98117,919000.0,2009
1013,3,3.5,1680.0,sqft,1486.0,sqft,98126,675000.0,2010
1014,3,2.0,1370.0,sqft,21780.0,sqft,98112,910000.0,2012
1015,4,2.0,2140.0,sqft,6250.0,sqft,98199,1150000.0,2014
1016,3,2.0,1710.0,sqft,4267.0,sqft,98133,659000.0,2016

In [101]:
df.isnull().sum()   ## data frame has 0 nulls

beds              0
baths             0
size              0
size_units        0
lot_size          0
lot_size_units    0
zip_code          0
price             0
index             0
dtype: int64

In [102]:
df.shape

(1017, 9)

In [103]:
df2 = df[['beds',	'baths'	,'size',	'size_units',	'lot_size',	'lot_size_units',	'zip_code',	'price'	]]
df2

,beds,baths,size,size_units,lot_size,lot_size_units,zip_code,price
0,3,3.0,2850.0,sqft,4200.0,sqft,98119,1175000.0
1,3,2.0,2360.0,sqft,12196.8,sqft,98188,565000.0
2,3,3.5,1942.0,sqft,1603.0,sqft,98107,1187000.0
3,4,2.0,2060.0,sqft,4206.0,sqft,98144,1025000.0
4,3,2.5,1760.0,sqft,3630.0,sqft,98122,1135000.0
...,...,...,...,...,...,...,...,...
1012,3,2.0,1482.0,sqft,1085.0,sqft,98117,919000.0
1013,3,3.5,1680.0,sqft,1486.0,sqft,98126,675000.0
1014,3,2.0,1370.0,sqft,21780.0,sqft,98112,910000.0
1015,4,2.0,2140.0,sqft,6250.0,sqft,98199,1150000.0
1016,3,2.0,1710.0,sqft,4267.0,sqft,98133,659000.0

In [ ]:
## Removing unseen data

In [104]:

data = df2.sample(frac=0.95,random_state=28)
data_unseen = df2.drop(data.index)

print(f'Data for model: {data.shape},\nData for unseen predictions: { data_unseen.shape}')

Data for model: (966, 8),
Data for unseen predictions: (51, 8)

In [ ]:
## Data Prep

In [105]:
from pycaret.regression import *
reg = setup(data = data, target='price', normalize=True)
reg

In [ ]:
### Data Clean and removed  Nulls

In [106]:
df.isnull().sum()

beds              0
baths             0
size              0
size_units        0
lot_size          0
lot_size_units    0
zip_code          0
price             0
index             0
dtype: int64

In [ ]:
## comparing just the best and most effitient models.

In [107]:
best_model = compare_models(include = ['gbr','rf','huber','ridge'])
best_model

GradientBoostingRegressor(random_state=8930)

In [108]:
res = pull()
res

,Model,MAE,MSE,RMSE,R2,RMSLE,MAPE,TT (Sec)
gbr,Gradient Boosting Regressor,189366.9665,7.469069e+10,271487.1062,0.4684,0.2320,0.1861,2.772
rf,Random Forest Regressor,196635.0081,7.909525e+10,279617.8534,0.4345,0.2449,0.1968,1.995
ridge,Ridge Regression,214470.6745,8.516567e+10,290605.5180,0.3909,0.2622,0.2182,2.035
huber,Huber Regressor,215218.8237,8.565275e+10,291350.6863,0.3893,0.2620,0.2167,1.986

In [ ]:
## CREATE gbr MODEL

In [109]:
gbr = create_model('gbr')

Initiated  . . . . . . . . . . . . . . . . . .                     14:10:12
Status     . . . . . . . . . . . . . . . . . .             Fitting 10 Folds
Estimator  . . . . . . . . . . . . . . . . . .  Gradient Boosting Regressor

In [ ]:
# tunning model so I can compare

In [110]:
gbr_tuned_model = tune_model(gbr)

Initiated  . . . . . . . . . . . . . . . . . .                     14:11:36
Status     . . . . . . . . . . . . . . . . . .         Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .  Gradient Boosting Regressor

Fitting 10 folds for each of 10 candidates, totalling 100 fits

In [ ]:
## R2 IS 0.4418

In [ ]:
## Increasing the folds

In [113]:
gbr_tuned_model_new = tune_model(gbr, fold = 15)

Initiated  . . . . . . . . . . . . . . . . . .                     17:51:54
Status     . . . . . . . . . . . . . . . . . .         Loading Dependencies
Estimator  . . . . . . . . . . . . . . . . . .  Gradient Boosting Regressor

Fitting 15 folds for each of 10 candidates, totalling 150 fits

In [114]:
gb = pull()
gb

              MAE           MSE         RMSE      R2   RMSLE    MAPE
Fold
0     164462.3347  6.099614e+10  246973.9717  0.5510  0.1964  0.1407
1     215175.8003  1.296981e+11  360136.2325  0.2993  0.2635  0.1939
2     171814.3579  5.600847e+10  236661.0892  0.4438  0.2341  0.1963
3     207428.0621  7.193606e+10  268208.9868  0.4500  0.2422  0.2124
4     189909.1484  7.018806e+10  264930.2971  0.2470  0.2676  0.2241
5     189110.7594  5.455662e+10  233573.5953  0.5185  0.2341  0.2007
6     237198.8975  1.010309e+11  317853.6519  0.3106  0.2817  0.2249
7     198364.8219  5.876253e+10  242409.8296  0.4065  0.2551  0.2221
8     158544.9793  5.107988e+10  226008.5758  0.5226  0.2422  0.1863
9     154307.3559  5.340007e+10  231084.5619  0.4426  0.2100  0.1499
10    202153.1260  9.854083e+10  313912.1395  0.6491  0.2097  0.1622
11    216710.8940  1.046128e+11  323439.0571  0.5009  0.2358  0.1817
12    187692.6952  6.449218e+10  253953.1029  0.5795  0.2324  0.1919
13    233321.9322  1.091972e+11  330450.0377  0.1405  0.3027  0.2628
14    194210.4341  6.698733e+10  258819.1040  0.4760  0.2250  0.1745
Mean  194693.7066  7.676582e+10  273894.2822  0.4359  0.2422  0.1950
Std    24376.0605  2.409360e+10   41805.9883  0.1311  0.0274  0.0307

In [115]:
print(gbr)

GradientBoostingRegressor(random_state=8930)

In [116]:
final_model = finalize_model(gbr)
final_model

Pipeline(memory=FastMemory(location=C:\Users\juud0\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(include=['beds', 'baths', 'size',
                                             'lot_size', 'zip_code'],
                                    transformer=SimpleImputer())),
                ('categorical_imputer',
                 TransformerWrapper(include=['size_units', 'lot_size_units'],
                                    transformer=SimpleImputer(strategy='most_frequent'))),
                ('onehot_encoding',
                 TransformerWrapper(include=['size_units', 'lot_size_units'],
                                    transformer=OneHotEncoder(cols=['size_units',
                                                                    'lot_size_units'],
                                                              handle_missing='return_nan',
                                                              use_cat_names=True))),
                ('normalize', TransformerWrapper(transformer=StandardScaler())),
                ('actual_estimator',
                 GradientBoostingRegressor(random_state=8930))])

In [ ]:
## predict_model(gbr)

In [ ]:
## gbr,rf,huber,ridge

In [ ]:
### WORK BELOW IS INVALID THIS WAS PART OF MY ANALYSIS AND COMPARION... I HAVE DECIDED TO LEAVE IT HERE JUST INCASE I WANT TO CONTINUE OR REVIEW MY ANALYSIS

In [ ]:
### checking method 2

In [67]:
test = pd.read_csv ('test.csv')

In [68]:
train = pd.read_csv ('train.csv')

In [69]:
merged_df2 = pd.concat([test, train], ignore_index=True)
merged_df2

,beds,baths,size,size_units,lot_size,lot_size_units,zip_code,price
0,3,3.0,2850.0,sqft,4200.00,sqft,98119,1175000.0
1,4,5.0,3040.0,sqft,5002.00,sqft,98106,1057500.0
2,3,1.0,1290.0,sqft,6048.00,sqft,98125,799000.0
3,3,2.0,2360.0,sqft,0.28,acre,98188,565000.0
4,3,3.5,1942.0,sqft,1603.00,sqft,98107,1187000.0
...,...,...,...,...,...,...,...,...
2516,3,2.0,1370.0,sqft,0.50,acre,98112,910000.0
2517,1,1.0,889.0,sqft,NaN,NaN,98121,550000.0
2518,4,2.0,2140.0,sqft,6250.00,sqft,98199,1150000.0
2519,2,2.0,795.0,sqft,NaN,NaN,98103,590000.0
2520,3,2.0,1710.0,sqft,4267.00,sqft,98133,659000.0

In [81]:
merged_df2

,beds,baths,size,size_units,lot_size,lot_size_units,zip_code,price
0,3,3.0,2850.0,sqft,4200.00,sqft,98119,1175000.0
1,4,5.0,3040.0,sqft,5002.00,sqft,98106,1057500.0
2,3,1.0,1290.0,sqft,6048.00,sqft,98125,799000.0
3,3,2.0,2360.0,sqft,0.28,acre,98188,565000.0
4,3,3.5,1942.0,sqft,1603.00,sqft,98107,1187000.0
...,...,...,...,...,...,...,...,...
2516,3,2.0,1370.0,sqft,0.50,acre,98112,910000.0
2517,1,1.0,889.0,sqft,3896.00,sqft,98121,550000.0
2518,4,2.0,2140.0,sqft,6250.00,sqft,98199,1150000.0
2519,2,2.0,795.0,sqft,3896.00,sqft,98103,590000.0
2520,3,2.0,1710.0,sqft,4267.00,sqft,98133,659000.0

In [82]:
merged_df2.isnull().sum()

beds              0
baths             0
size              0
size_units        0
lot_size          0
lot_size_units    0
zip_code          0
price             0
dtype: int64

In [83]:
merged_df2['lot_size'].mean()

3896.204454581515

In [84]:
merged_df2['lot_size_units']

0       sqft
1       sqft
2       sqft
3       acre
4       sqft
        ...
2516    acre
2517    sqft
2518    sqft
2519    sqft
2520    sqft
Name: lot_size_units, Length: 2521, dtype: object

In [85]:
merged_df2['lot_size'] = merged_df2['lot_size'].fillna(3896)

In [86]:
merged_df2['lot_size_units'] = merged_df2['lot_size_units'].fillna('sqft')

In [87]:
merged_df2.isnull().sum()

beds              0
baths             0
size              0
size_units        0
lot_size          0
lot_size_units    0
zip_code          0
price             0
dtype: int64

In [89]:
merged_df2.shape

(2521, 8)

In [90]:
data_unseen = merged_df2.sample(n=127, random_state = 28)
merged_df2 = merged_df2.drop(data_unseen.index)

print(f'Data for model: {merged_df2.shape},\nData for unseen predictions: { data_unseen.shape}')

Data for model: (2394, 8),
Data for unseen predictions: (127, 8)

In [ ]:

## data = df2.sample(frac=0.95,random_state=28)
## data_unseen = df2.drop(data.index)

## print(f'Data for model: {data.shape},\nData for unseen predictions: { data_unseen.shape}')

In [91]:
from pycaret.regression import *
s = setup(data = merged_df2, target='price', normalize=True)
s

In [92]:
best2 = compare_models()
best2

Initiated  . . . . . . . . . . . . . . . . . .           13:33:54
Status     . . . . . . . . . . . . . . . . . .  Loading Estimator
Estimator  . . . . . . . . . . . . . . . . . .  Compiling Library

HuberRegressor()

In [94]:
results = pull()
results

,Model,MAE,MSE,RMSE,R2,RMSLE,MAPE,TT (Sec)
huber,Huber Regressor,251012.3106,8.386998e+11,6.731316e+05,0.4672,0.3353,0.2432,1.563
ridge,Ridge Regression,265019.7337,8.365964e+11,6.742735e+05,0.4632,0.3592,0.2869,1.409
lr,Linear Regression,265067.4239,8.366077e+11,6.743067e+05,0.4631,0.3593,0.2870,2.362
lasso,Lasso Regression,265067.0940,8.366075e+11,6.743064e+05,0.4631,0.3593,0.2870,1.536
lar,Least Angle Regression,265067.4239,8.366077e+11,6.743067e+05,0.4631,0.3593,0.2870,1.513
llar,Lasso Least Angle Regression,265067.0955,8.366075e+11,6.743064e+05,0.4631,0.3593,0.2870,1.529
omp,Orthogonal Matching Pursuit,264922.1760,8.420664e+11,6.795519e+05,0.4513,0.3462,0.2808,1.431
en,Elastic Net,282615.6113,8.564023e+11,6.940535e+05,0.4178,0.3666,0.3123,1.396
par,Passive Aggressive Regressor,266147.2874,8.729478e+11,7.061185e+05,0.3914,0.3471,0.2400,1.616
knn,K Neighbors Regressor,266495.4984,9.003966e+11,7.508226e+05,0.2511,0.3435,0.2685,1.534
rf,Random Forest Regressor,257009.9688,9.381999e+11,7.713843e+05,0.1472,0.3432,0.2693,1.944
gbr,Gradient Boosting Regressor,253836.1033,9.132815e+11,7.566121e+05,0.1471,0.3385,0.2599,1.734
ada,AdaBoost Regressor,299946.2486,9.063974e+11,7.527757e+05,0.1352,0.3909,0.3535,1.631
br,Bayesian Ridge,387470.8813,9.832754e+11,8.317706e+05,-0.0018,0.5115,0.4812,1.414
dummy,Dummy Regressor,420787.9781,1.007820e+12,8.381670e+05,-0.0084,0.5433,0.5280,1.470
et,Extra Trees Regressor,258177.9542,1.087958e+12,8.188894e+05,-0.3183,0.3387,0.2698,1.758
dt,Decision Tree Regressor,320365.6461,1.644282e+12,1.031222e+06,-1.9087,0.4054,0.3515,1.428